### PR TITLE
Css data flow selection

### PR DESCRIPTION
**Pull request by sevisal**
# Purpose
Define data flow between the modules.

## In brief
- Defined the input data for each module
- Defined the output data for the pipeline
- Added options to store more than one module's output

# Data passing
Each module defines which data it should use as input. In particular, it can either use load existing data from an specificed folder or use the output of the desired previously executed module.

### XML tags
The tag `inputdata` is now added to each module and indicates what data should be used as input for the module. It accepts three different options, namely `file`, `folder` and `module`. While the first two options load the data from an specified path, the third option expects a string that corresponds to the name of an existing module.
```XML
<Modelling name="Modelling">
    <inputdata>
      <X module="Initialiser" />
    </inputdata>
</Modelling>
```
### GUI
When indicating the plugin for each module it also asks for the input data for that module. To do so, it displays a dropdown menu with the available modules, with the expection of itself and the output module. By default it proposes the output from the previous module.
<p align="center">

</p>

## Output data
The output module now defines what and where data should be stored. The output module now defines what and where data should be stored.
### XML tags
The `Output` module has two tags dedicated to define the output of the pipeline. The `outdata` tag expects a set of module names separated in different lines that will be loaded as a list. This leads to storing the output data of the indicated modules. The `outpath` tag defines the file where the output should be stored. It works absolute paths and also with paths relative to the `ai-assisted-design-framework\src\vai_lab\` folder. Currently, it only allows storing the data in a _pickle_ (_.pkl_) file due to its storing versatility.

```XML
    <Output name="Output">
        <plugin type="Output">
            <outdata>
                Data Processing
                Modelling
            </outdata>
            <outpath>
                 .\examples\results\output.pkl
            </outpath>
        </plugin>
    </Output>
```

## GUI
The plugin selection part of the GUI now allows defining the modules' output that we want to store. There are tick boxes that indicate for each module if its output should be stored or not. By default only the output of the last module is stored. Then there is a browsing option to select where and with witch name to store the output.
<p align="center">

</p>

### CODE REVIEW

**Comment by teemu-ruokolainen** [comment]
Overall, the approach seems sound (read input from file/folder or take from another module I'm assuming in-memory + option to write module outputs to disk for later reading). The xml example is not completely clear to me, I think I would benefit from a more "real life" example?

Note: Are the `.DS_store` files going to the git repo on purpose? These are MacOS specific data storage files and (usually) added to .gitignore. If they are not supposed to be there, I can clean the branch from them, push, and then you can merge.

**Comment by sevisal** [comment]
What did you have in mind? The examples we currently have are just the previous ones but I adapted them to the new data flow definition.

I have never used MacOS before, I don't know how they got there. I guess we could clean it.

**Comment by teemu-ruokolainen** [comment]
>What did you have in mind? The examples we currently have are just the previous ones but I adapted them to the new data flow definition.

Ah ok, let's leave it as is then for now. (I was thinking of maybe a two step pipeline with input, data transfer between modules, and output. Now they seem to be disconnected.)

>I have never used MacOS before, I don't know how they got there. I guess we could clean it.

Ok, I will clean them and push.

**Comment by sevisal** [comment]
> Ah ok, let's leave it as is then for now. (I was thinking of maybe a two step pipeline with input, data transfer between modules, and output. Now they seem to be disconnected.)
There are some that do what, I believe, you described. For example, `scaler-lasso_demo.xml` has input data, two module data communication and stores the output of two modules.

**Comment by teemu-ruokolainen** [comment]
These were removed:

rm 'src/vai_lab/examples/crystalDesign/phasestability/.DS_Store'
rm 'src/vai_lab/examples/crystalDesign/phasestability/CsFA/.DS_Store'
rm 'src/vai_lab/examples/crystalDesign/phasestability/CsMA/.DS_Store'
rm 'src/vai_lab/examples/crystalDesign/phasestability/FAMA/.DS_Store'

and .DS_Store added to .gitignore.

**Comment by sevisal** [comment]
Let's remove the crystalDesign folder, it should be merged on a different PR anyway (it's supposed to be in the `css-MaterialDesign` branch)

**Review by teemu-ruokolainen — APPROVED** [review]
I think this is now clean enough to be merged (using SQUASH).

**Pull request merged**
