### PR TITLE
Add rough sphinx documentation

### PR DESCRIPTION
**Pull request by teemu-ruokolainen**
This PR is for previewing and for discussion! 

PR adds structure for Sphinx documentation:
- docs folder contains everything documentation related (configuration, templates, sources)
- workflow to generate the documentation at pull request: .github/workflows/documentation.yml

At the moment, the documentation contains README.md (direct import) and an API documentation generated automatically from available docstrings.

Potential enhancement steps (for discussion):

- split README.md into subsections, convert markdown to restructure text (sphinx format) and make each of them its own documentation section (Install, Usage, Contribution Guide, etc.)
- identify portion of the code comprising API (aka "public methods and classes") and improve/clean up docstring coverage for this part (exclude private code from documentation)

### CODE REVIEW

**Comment by cam586** [comment]
This is a great start, thanks Teemu! I haven't used sphinx much  before - is there a way to view the generated docs after the workflow has run?

**Comment by sevisal** [comment]
Agree, it sounds amazing. Thanks for taking the time to build this! 
I don't know how to visualise it either, sorry.

**Comment by sevisal** [comment]
Thanks Teemu I have checked it and it looks great. There are a few items in the index list that overflow the column but that's the only issue I have found.

**Comment by cam586** [comment]
Merging with minor changes to files which were sphinx warnings and added a readme badge for docs building

**Review by cam586 — APPROVED** [review]

**Pull request merged**
